image: maven:3.6.3-jdk-11

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:
        - .m2/repository


Build project:
    stage: build
    script:
        - mvn $MAVEN_OPTS compile

Test project:
    stage: test
    script:
        - mvn $MAVEN_OPTS test
    artifacts:
        paths:
            - target/surefire-reports/TEST-*.xml
        reports:
            junit: target/surefire-reports/TEST-*.xml
