image: maven:3.6.3-jdk-11

stages:
  - build
    #    - test

    #variables:
    #    POSTGRES_DB:
    #    POSTGRES_USER:
    #    POSTGRES_PASSWORD:


default:
  timeout: 5m

build:
  stage: build
  script:
    - echo 'Statring building...'
    - mvn clean compile
  only:
    - merge_requests

#test:
#    stage: test
#    script:
#        - echo 'Starting testing...'
#        - mvn clean test
#    only:
#        - merge_requests  