spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
      port: 587
      username: mymailproject@gmail.com
      password: mypassword
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com