spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  server:
    servlet:
      contextPath: /api/v1

  mail:
    host: smtp.gmail.com
    port: 587
    username: socialnetwok2021@gmail.com
    password: sizadrhjufeacfpw
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

cloudinary:
  url: cloudinary://889892999924949:HBEMk4_4zYqvw8Eg6e2vwqDQxy4@dmw3gspng